import torch


def int4Matmul(A: torch.Tensor, B: torch.Tensor) -> torch.Tensor: ...

def int8Matmul(A: torch.Tensor, B: torch.Tensor) -> torch.Tensor: ...

def int4SpMatmul(A: torch.Tensor, B: torch.Tensor, E: torch.Tensor) -> torch.Tensor: ...


def reorderMeta(E: torch.Tensor) -> torch.Tensor: ...
